import { makeStyles } from "@material-ui/styles";

export default makeStyles((theme) => ({
  centerText: {
    position: "fixed",
    fontSize: "25px",
    top: "33.3%",
    bottom: "33.3%",
    left: "34%",
    right: "32%",
  },
  dialogAvatar: {
    marginRight: "5px",
    backgroundColor: "#3f51b5",
  },
  emailAnchor: {
    color: "blue",
    fontSize: "13px",
  },

  footerBar: {
    color: "#000000",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "83%",
    position: "fixed",
    bottom: "0px",
    right: "0px",
    //left: "0px",
    height: "20px",
    fontWeight: "bold",
    fontSize: "14px",
    // boxShadow: "0 2px 15px 0 rgba(0,0,0,.05)!important",
    boxShadow: 20,
    //backgroundColor: "#F0F0F0",
  },

  Login: {
    width: "100px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  drawerOpen: {
    width: 250,
    position: "fixed",
    top: 0,
    bottom: 0,
    borderRadius: "0px",
    overflow: "auto",
  },
  DrawerItem: {
    height: "22px",
    marginTop: "10px",
    marginBottom: "15px",
  },
  root: {
    position: "relative",
  },
  dropdown: {
    position: "absolute",
    right: 35,
    width: 300,
    height: 250,
    top: 45,
    zIndex: 1,
    border: "1px solid",
    padding: theme.spacing(1),
    backgroundColor: theme.palette.background.paper,
  },
  centerDisplay: {
    position: "fixed",
    left: "39%",
    right: "39%",
    top: "25vh",
    // bottom: "25vh",
    paddingTop: 20,
    paddingBottom: 20,
    paddingLeft: 10,
    paddingRight: 10,
  },
  appbarBrand: {
    width: "33.3%",
    display: "flex",
    justifyContent: "center",
    padding: "5px",
    position: "absolute",
    left: "33.3%",
    right: "33.3%",
    fontSize: "20px",
  },
  avatar: { position: "absolute", right: "0px" },
  emailAnchor: {
    color: "blue",
    fontSize: "13px",
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "flex-start",
  },

  appbarBrand: {
    width: "25%",
    height: "33.3%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    left: "33.3%",
    right: "33.3%",
    fontSize: "20px",
  },
  select: {
    "& .MuiSvgIcon-root": {
      color: "white",
    },
  },

  headerContainer: {
    width: "100%",
    height: "50px",
    padding: "7px",
    fontSize: "18px",
    position: "relative",
  },
  formData: {
    position: "relative",
    width: "79%",
    marginLeft: 270,
    marginBottom: "40px",
    marginTop: 20,
    marginRight: 3,
  },

  headerText: {
    position: "absolute",
    left: "10px",
    fontSize: "20px",
  },
  selectClass: { textAlign: "left" },
  inactiveStep: {
    textAlign: "left",
    padding: "20px",
    margin: "-26px 0px -26px -20px",
  },

  spinner: {
    position: "fixed",
    top: "33.3%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    bottom: "33.3%",
    left: "33.3%",
    right: "33.3%",
    fontSize: "100px",
  },
  formButton: {
    display: "flex",
    justifyContent: "flex-end",
    margin: "10px",
  },
  inactiveStep: {
    textAlign: "left",
    padding: "20px",
    margin: "-26px 0px -26px -20px",
  },
  activeStep: {
    textAlign: "left",
    background: "#dbe9fe",
    padding: "20px",
    marginLeft: "-20px",
  },
  stepperButton: {
    marginTop: "10px",
    float: "right",
    marginRight: "-13px",
  },
  circularProgress: {
    position: "absolute !important",
    top: "5px !important",
    height: "21px !important",
    width: "21px !important",
  },
}));
